# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CD

on:
  push:
    branches: [ main ]
  # Uncomment the 'pull_request' line below to manually trigger the workflow
  # pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create credentials file
      run: |
        python ./src/create_json_credentials.py
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Google sheet from repository
      run: |
        python ./src/create_database_gsheet.py
